-- NexSpace Data Consistency Migration
-- Generated on: 2025-07-29T04:45:16.485Z

-- Create associations for orphaned facility users
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (20, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (25, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (11, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (17, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (12, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (10, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (18, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (15, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (13, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (21, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (19, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (24, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (8, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (16, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (23, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (23, 19);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (22, 3);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (14, 1);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (9, 2);
INSERT INTO facility_user_facility_associations (facility_user_id, facility_id) VALUES (7, 1);

-- Assign default facility to staff
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 49;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 50;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 78;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 3;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 7;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 13;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 9;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 17;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 20;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 30;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 35;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 42;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 37;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 53;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 55;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 57;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 40;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 41;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 43;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 44;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 45;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 46;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 47;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 66;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 80;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 63;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 65;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 68;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 70;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 72;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 74;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 54;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 58;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 76;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 1;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 2;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 4;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 5;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 6;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 8;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 10;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 11;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 12;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 14;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 15;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 16;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 18;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 19;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 21;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 22;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 23;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 24;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 25;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 26;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 27;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 28;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 29;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 31;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 32;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 33;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 34;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 36;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 38;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 39;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 48;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 51;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 59;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 52;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 60;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 61;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 62;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 79;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 64;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 67;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 69;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 71;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 73;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 75;
UPDATE staff SET associated_facilities = '[1]'::jsonb WHERE id = 77;

